feat(strategy): add undefined strategy
gcornut/valibot-json-schema pull request #15
Opened 2024-02-07 08:03 UTC by qlaffont

ref https://github.com/gcornut/valibot-json-schema/issues/14

2024-02-07 18:48 UTC, gcornut requested changes
I have two minor changes 
Also can you run `yarn lint --apply` before commit to properly format all the code ?

2024-02-07 18:48 UTC, gcornut commented on src/toJSONSchema/schemas.ts
> +            throw new Error('The "undefinedStrategy" option must be set to handle date validators');
A small oversight
```suggestion
            throw new Error('The "undefinedStrategy" option must be set to handle the `undefined` schema');
```

2024-02-07 18:48 UTC, gcornut commented on src/toJSONSchema/schemas.ts
> +                return {}
Looks like `custom` is exactly like `any`. Maybe we should only have the `any` strategy for now ?

2024-02-08 10:00 UTC, qlaffont commented
done ^^

2024-02-08 11:13 UTC, gcornut approved these changes

2024-02-08 11:17 UTC, merged